#! /bin/sh
# Demo script for tdinterp
# Pascal Getreuer 2011

# Image credits: the test image frog-hr.bmp is by
#   John D. Willson, USGS Amphibian Research and Monitoring Initiative
#   http://armi.usgs.gov/gallery/detail.php?search=Genus&subsearch=Bufo&id=323

# Echo shell commands
set -v

# Set parameters
factor=4
sigma=0.5

# First, we coarsen high resolution image "frog-hr.bmp" by factor 4 to make
# low resolution image "frog-lr.bmp".
./imcoarsen -g topleft -x$factor -p$sigma frog-hr.bmp frog-lr.bmp

# Now we run the interpolation on the coarsened image "frog-lr.bmp"...
./tdinterp -x$factor -p$sigma frog-lr.bmp interp.bmp

# Compute difference between the original and the interpolation
./imdiff frog-hr.bmp interp.bmp
